CREATE FUNCTION `RoundTo0_5`(Pnum DOUBLE) RETURNS double
    NO SQL
    DETERMINISTIC
BEGIN
	DECLARE z, r DOUBLE;
	SET z=TRUNCATE(Pnum, 0);
	SET r=ROUND(Pnum-z, 1);
	CASE
		WHEN r>0.2 AND r<=0.7 THEN SET r=0.5;
		WHEN r>0.7 THEN SET r=1;
		ELSE SET r=0;
	END CASE;
	RETURN z+r;
END$$

DELIMITER ;
